Fix 'jni_md.h: No such file or directory' error when building on Ubuntu 16.04 LTS
When building Android on Ubuntu 16.04 LTS, this fixes an error for a missing header file:
In file included from ./src/android/io_realm_react_RealmReactModule.cpp:19:0:
/usr/lib/jvm/java-8-oracle/include/jni.h:45:20: fatal error: jni_md.h: No such file or directory
                   ^
compilation terminated.
make: *** [/home/ashwinp/projects/realm-js/react-native/android/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs-debug/realmreact/src/android/io_realm_react_RealmReactModule.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/home/ashwinp/projects/realm-js/react-native/android/src/main/jni'
:buildReactNdkLib FAILED

FAILURE: Build failed with an exception.